### PR TITLE
Do docker things in the Dockerfile and apt things in the script.

### PR DESCRIPTION
**Pull request by mbruzek**
Addresses issue #37

### CODE REVIEW

**Comment by lazypower** [comment]
docker :cop: does not like that you've left build-essential installed, as that is going to bloat the image quite a bit. Can you remove the build tools after you've installed the dependencies?

**Comment by mbruzek** [comment]
Thanks for the review @chuckbutler. Since charmbox this is used for "building" charms so I think there are things we need from build essential package.  If you look at the diff build-essential is on both sides, I just reordered the list of packages. I did neglect to remove gcc and cython which was removed from the Dockerfile (fixing that in a moment).

**Comment by lazypower** [comment]
Actually I change my vote on the last review. Bundletester expects all kinds of things from build-essential to be installed. Its a 40mb difference, which is suppose is small enough to pay forward into the image. It beats fetching the packages every time

**Comment by lazypower** [comment]
I believe this was superseded by #40 

Closing this for now. Please re-open if there is reason.

**Comment by mbruzek** [comment]
It may be true that issue #37 is fixed, but we still do a mix of apt-get in the docker file and in the scripts.  It would be cleaner to separate concerns at some point in the future.

**Comment by lazypower** [comment]
@mbruzek - rebase this PR please and lets merge it

**Pull request closed without merging**
